name: Cypress Tests and Code Coverage

on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["development"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Setup Code Climate test-reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Install dependencies
        run: yarn
      - name: Cypress CI run
        run: yarn cypress:ci
      - name: Publish code coverage
        run: |
          export GIT_BRANCH="${GITHUB_HEAD_REF}"
          ./cc-test-reporter after-build -r ${{secrets.CC_TEST_REPORTER_ID}}

